### ISSUE TITLE
Have the build options for DSO138 been tested?

### ISSUE THREAD

**Issue by kennpie** [michar71/Open-DSO-150#14]
Hi,
I was trying to build this to try on my DSO138.

I commented out the following defines in global.h:
#define DSO_150
#define ADD_AN2
#define ADD_D3
#define USE_ENCODER

... then built, and I got a number of build errors, most centering around variables that are defined for DSO150, but not for DSO138 (eg RNG_20V,RNG_10V, RNG_5mV), yet they're used elsewhere.

I did confirm that the original options for DSO150 would build, before I made changes to global.h, so I believe I've got the right board and libraries selected (STM32F103C8). Also, I'm able to build from the project you forked (ardyesp/DLO-138).

Do you see anything wrong with my assumptions, or is it just the case that building your code for DSO138 is currently untested, and will need some fixes?

Thanks!

**Comment by michar71** [comment]
Sorry, DSO-138 is no longer supported... (Just too many differences and I don't have one for testing....)
