### ISSUE TITLE
Warnings when compiling 

### ISSUE THREAD

**Issue by MikeLud** [michar71/Open-DSO-150#26]
When compiling I am getting 20 warnings (see below). I did not try flashing yet. Is this normal or something is wrong.
![image](https://user-images.githubusercontent.com/36526272/49690839-58525880-fb05-11e8-8893-935b7fffd64f.png)

**Comment by michar71** [comment]
Yea, those are expected. (Probably will clean that up one day...)

**Comment by MikeLud** [comment]
@michar71 

Thanks for the response, I will try flashing over the weekend.
